### ISSUE TITLE
Add support for tracking Akka.Cluster.Sharding `ShardRegion` metrics

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/phobos-issues#72]
We should add support for:

- [x] Enumerating all `ShardRegion`s by name
- [x] Tracking the number of shards / entities per `ShardRegion`
- [x] Tracking the shard / entities per `ShardRegion` per `Address` / `role`

I think this should be pretty straightforward to do within the Phobos.Actor.Cluster module.

**Comment by Aaronontheweb** [comment]
We've added dashboard support for this in Prometheus and will do the same for other supported platforms: https://github.com/petabridge/phobos-dashboards/pull/22
